{
  pkgs,
  deckUser,
  deckUid,
}:

{ ... }:
{
  documentation.nixos.enable = false;

  networking.hostName = "deck";
  time.timeZone = "UTC";
  i18n.defaultLocale = "en_US.UTF-8";

  virtualisation = {
    graphics = false;
    memorySize = 3072;
    cores = 2;
  };

  boot.kernelModules = [
    "fuse"
    "uinput"
  ];

  users.users.${deckUser} = {
    isNormalUser = true;
    uid = deckUid;
    description = "Steam Deck AppImage integration test user";
    createHome = true;
    home = "/home/${deckUser}";
    extraGroups = [ "input" ];
  };

  services.dbus.enable = true;
  security.polkit.enable = true;
  services.udev.enable = true;

  environment.systemPackages = [
    pkgs.acl
    pkgs.coreutils
    pkgs.curl
    pkgs.fuse3
    pkgs.iproute2
    pkgs.procps
    pkgs.systemd
    pkgs.util-linux
  ];

  # NixOS compiles systemd with only its own bin directory as the default
  # PATH. SteamOS units that are not generated by NixOS see /usr/bin.
  systemd.settings.Manager.DefaultEnvironment = "PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:${pkgs.systemd}/bin";

  # The AppImage intentionally installs distribution-neutral units whose
  # ExecStartPre paths follow the /usr/bin layout present on SteamOS.
  # Supply those host tools without installing Keymasq from Nix.
  system.activationScripts.keymasqAppimageHostCompatibility.text = ''
    materialize_etc_tree() {
      path=$1
      if [ -L "$path" ]; then
        staged=$(mktemp -d)
        cp -a "$path/." "$staged/"
        rm "$path"
        mv "$staged" "$path"
      else
        install -d -m 0755 "$path"
      fi
    }

    # NixOS generates these as immutable /etc/static symlink trees.
    # SteamOS and the other AppImage targets expose writable directories,
    # so materialize their current contents in this disposable VM.
    materialize_etc_tree /etc/systemd/system
    materialize_etc_tree /etc/udev/rules.d

    install -d -m 0755 /bin
    ln -sfn ${pkgs.util-linux}/bin/mount /bin/mount
    ln -sfn ${pkgs.util-linux}/bin/umount /bin/umount
    install -d -m 0755 /usr/bin
    ln -sfn ${pkgs.bash}/bin/sh /usr/bin/sh
    ln -sfn ${pkgs.acl}/bin/setfacl /usr/bin/setfacl
    ln -sfn ${pkgs.systemd}/bin/udevadm /usr/bin/udevadm
    # Root ExecStartPre steps run the AppImage runtime script, which
    # resolves ordinary host tools through systemd's default PATH.
    for tool in ${pkgs.coreutils}/bin/*; do
      ln -sfn "$tool" "/usr/bin/''${tool##*/}"
    done
    ln -sfn ${pkgs.diffutils}/bin/cmp /usr/bin/cmp
    ln -sfn ${pkgs.gawk}/bin/awk /usr/bin/awk
    ln -sfn ${pkgs.gnugrep}/bin/grep /usr/bin/grep
    ln -sfn ${pkgs.systemd}/bin/systemctl /usr/bin/systemctl
  '';
}
