# Generated by `python3 packaging/pacman/render.py`.
# Do not edit this file directly; update `packaging/pacman/templates/`.

# Maintainer: nyrda <nyrda@keymasq.tools>
pkgname=keymasq
pkgver=0.4.0
pkgrel=1
pkgdesc="A key remapping tool for Linux using evdev and uinput"
arch=(
    'any'
)
url="https://github.com/nyrda/keymasq"
license=(
    'MIT'
)
depends=(
    'acl'
    'slurp'
    'python>=3.12'
    'python-evdev>=1.6.0'
    'python-tomli-w>=1.0.0'
    'python-dbus-next>=0.2.3'
    'python-xlib>=0.33'
    'python-gobject>=3.42.0'
    'gtk4'
    'libadwaita'
    'polkit'
    'systemd'
)
makedepends=(
    'python-setuptools>=61.0'
    'python-wheel'
    'python-build'
    'python-installer'
)
optdepends=(
    'hyprland: for Hyprland window rule support'
    'niri: for Niri window rule support'
)
install="$pkgname.install"
source=()
sha256sums=()

prepare() {
    local worktree_dir="$srcdir/$pkgname-$pkgver"

    rm -rf "$worktree_dir"
    mkdir -p "$worktree_dir"

    shopt -s dotglob nullglob
    local entry
    local base_name
    for entry in "$startdir"/*; do
        base_name="${entry##*/}"
        case "$base_name" in
            .git|.direnv|.mypy_cache|.pytest_cache|.ruff_cache|.venv|dist|pkg|src|*.pkg.tar.*|*.src.tar.*)
                continue
                ;;
        esac
        cp -a "$entry" "$worktree_dir"/
    done
    shopt -u dotglob nullglob
}
build() {
    local build_root="$srcdir/$pkgname-$pkgver"

    rm -rf "$srcdir/python-dist"
    mkdir -p "$srcdir/python-dist"

    cd "$build_root"
    python -m build --wheel --no-isolation --outdir "$srcdir/python-dist"
}

package() {
    local build_root="$srcdir/$pkgname-$pkgver"

    cd "$build_root"

    python -m installer --destdir="$pkgdir" "$srcdir"/python-dist/*.whl

    install -Dm644 "assets/io.github.nyrda.Keymasq.desktop" \
        "$pkgdir/usr/share/applications/io.github.nyrda.Keymasq.desktop"
    install -Dm644 "assets/io.github.nyrda.Keymasq.metainfo.xml" \
        "$pkgdir/usr/share/metainfo/io.github.nyrda.Keymasq.metainfo.xml"
    install -Dm644 "assets/io.github.nyrda.Keymasq.svg" \
        "$pkgdir/usr/share/icons/hicolor/scalable/apps/io.github.nyrda.Keymasq.svg"
    local icon
    local size
    for icon in assets/icons/io.github.nyrda.Keymasq-*.png; do
        size="${icon##*-}"
        size="${size%.png}"
        install -Dm644 "$icon" \
            "$pkgdir/usr/share/icons/hicolor/${size}x${size}/apps/io.github.nyrda.Keymasq.png"
    done

    install -Dm644 "systemd/keymasqd.service" \
        "$pkgdir/usr/lib/systemd/system/keymasqd.service"
    install -Dm644 "systemd/keymasq-session.service" \
        "$pkgdir/usr/lib/systemd/user/keymasq-session.service"

    install -Dm644 "sysusers.d/keymasq.conf" \
        "$pkgdir/usr/lib/sysusers.d/keymasq.conf"
    install -Dm644 "tmpfiles.d/keymasq.conf" \
        "$pkgdir/usr/lib/tmpfiles.d/keymasq.conf"

    install -Dm644 "udev/91-keymasq-acl.rules" \
        "$pkgdir/usr/lib/udev/rules.d/91-keymasq-acl.rules"

    install -Dm644 "polkit/com.keymasq.record-macro.policy" \
        "$pkgdir/usr/share/polkit-1/actions/com.keymasq.record-macro.policy"

    install -Dm644 "LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
    install -Dm644 "README.md" "$pkgdir/usr/share/doc/$pkgname/README.md"
    install -Dm644 "examples/security.toml" \
        "$pkgdir/usr/share/doc/$pkgname/security.toml"

    install -d "$pkgdir/usr/share/gnome-shell/extensions/keymasq-bridge@nyrda"
    cp -a "gnome-extension/keymasq-bridge@nyrda/." \
        "$pkgdir/usr/share/gnome-shell/extensions/keymasq-bridge@nyrda/"

    rm -f "$pkgdir/usr/bin/keymasq-cli" "$pkgdir/usr/bin/keymasq-gui"
}
