from support import ScenarioCase

from . import (
    analog_mouse_area,
    analog_mouse_velocity,
    analog_multi_control,
    analog_priority_override,
    analog_profile_reset,
    analog_restart_recovery,
    analog_signed_axis_mouse,
    analog_signed_axis_threshold,
    analog_stick_gamepad,
    analog_stick_gamepad_invert,
    analog_threshold_hysteresis,
    analog_trigger_deadzone,
    cancel_macro_playback,
    combo_chord,
    combo_cross_device_transition_order,
    combo_negative_timeout,
    combo_prefix_overlap,
    combo_superkey,
    combo_superkey_recall_restore,
    emergency_reset,
    extended_keyboard_outputs,
    gamepad_axis_output,
    gamepad_output,
    held_output_profile_change,
    hotplug_replug,
    macro_lifecycle,
    macro_playback,
    mouse_output,
    multi_source_combo,
    multi_step_combo,
    passthrough_fallback,
    profile_lifetime_combos,
    profile_lifetime_direct,
    profile_lifetime_superkeys,
    profile_lifetime_toggle,
    profile_toggle,
    rapidfire_keyboard,
    recording_capture,
    repeat_combo_superkey,
    repeat_direct_actions,
    repeat_passthrough,
    restart_recovery,
    simple_remap,
    superkey_overload_multi_action,
    superkey_tap,
    suppress,
    tap_enabled,
)

SCENARIOS = [
    ScenarioCase("repeat direct mapped actions", repeat_direct_actions.run),
    ScenarioCase("repeat original passthrough input", repeat_passthrough.run),
    ScenarioCase("repeat combos and superkeys", repeat_combo_superkey.run),
    ScenarioCase("simple 1->1 remap", simple_remap.run),
    ScenarioCase("extended keyboard outputs", extended_keyboard_outputs.run),
    ScenarioCase("suppress", suppress.run),
    ScenarioCase("tap-enabled keyboard action", tap_enabled.run),
    ScenarioCase("rapidfire keyboard action", rapidfire_keyboard.run),
    ScenarioCase("macro playback", macro_playback.run),
    ScenarioCase("cancel macro playback", cancel_macro_playback.run),
    ScenarioCase("macro lifecycle", macro_lifecycle.run),
    ScenarioCase("superkey tap", superkey_tap.run),
    ScenarioCase(
        "superkey overload multi-action press/release",
        superkey_overload_multi_action.run,
    ),
    ScenarioCase("combo chord", combo_chord.run),
    ScenarioCase(
        "combo cross-device transition order",
        combo_cross_device_transition_order.run,
    ),
    ScenarioCase("combo bound to superkey", combo_superkey.run),
    ScenarioCase("combo superkey recall and restore", combo_superkey_recall_restore.run),
    ScenarioCase("multi-step combo", multi_step_combo.run),
    ScenarioCase("combo negative and timeout", combo_negative_timeout.run),
    ScenarioCase("prefix and overlapping combos", combo_prefix_overlap.run),
    ScenarioCase("multi-source combo", multi_source_combo.run),
    ScenarioCase("profile toggle", profile_toggle.run),
    ScenarioCase("profile lifetime direct actions", profile_lifetime_direct.run),
    ScenarioCase("profile lifetime toggle actions", profile_lifetime_toggle.run),
    ScenarioCase("profile lifetime superkeys", profile_lifetime_superkeys.run),
    ScenarioCase("profile lifetime combos", profile_lifetime_combos.run),
    ScenarioCase("passthrough overrides lower-profile mapping", passthrough_fallback.run),
    ScenarioCase("held output profile change", held_output_profile_change.run),
    ScenarioCase("mouse output", mouse_output.run),
    ScenarioCase("gamepad output", gamepad_output.run),
    ScenarioCase("gamepad axis output", gamepad_axis_output.run),
    ScenarioCase("analog stick to gamepad stick", analog_stick_gamepad.run),
    ScenarioCase("analog stick to gamepad stick invert", analog_stick_gamepad_invert.run),
    ScenarioCase("analog trigger deadzone", analog_trigger_deadzone.run),
    ScenarioCase("analog threshold hysteresis", analog_threshold_hysteresis.run),
    ScenarioCase("analog signed axis threshold ranges", analog_signed_axis_threshold.run),
    ScenarioCase("analog state reset on profile change", analog_profile_reset.run),
    ScenarioCase("multiple analog controls on one source", analog_multi_control.run),
    ScenarioCase("analog stick to mouse area", analog_mouse_area.run),
    ScenarioCase("analog stick to mouse velocity", analog_mouse_velocity.run),
    ScenarioCase("analog signed axis mouse horizontal", analog_signed_axis_mouse.run),
    ScenarioCase("analog priority override", analog_priority_override.run),
    ScenarioCase("analog restart recovery", analog_restart_recovery.run),
    ScenarioCase("emergency reset", emergency_reset.run),
    ScenarioCase("mapped macro slot actions", recording_capture.run_mapped_slot_actions),
    ScenarioCase("recording and capture", recording_capture.run),
    ScenarioCase("restart recovery", restart_recovery.run),
    ScenarioCase("hotplug replug", hotplug_replug.run),
    ScenarioCase(
        "mapped macro slot playback without capture unlock",
        recording_capture.run_mapped_slot_playback_without_unlock,
    ),
]
