#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'EOF'
Usage: create-libvirt-autopkgtest-vm.sh [options]

Create a Debian cloud-image VM on qemu:///system for autopkgtest use.

Options:
  --name NAME            Domain name (default: debian-trixie-autopkgtest)
  --release RELEASE      Debian release: trixie or bookworm (default: trixie)
  --pool NAME            Libvirt storage pool for the VM disk (default: pool)
  --cache-dir PATH       Directory for downloaded cloud images
                         (default: \$XDG_CACHE_HOME/keyforge/autopkgtest-libvirt)
  --seed-dir PATH        Directory for generated cloud-init seed disks
                         (default: /tmp/keyforge-autopkgtest-seeds)
  --memory MiB           VM memory in MiB (default: 2048)
  --vcpus COUNT          Number of vCPUs (default: 2)
  --size GiB             VM disk size in GiB (default: 20)
  --user USER            Login user for autopkgtest (default: autopkgtest)
  --password PASSWORD    Login password; autogenerated if omitted
  --network NAME         Libvirt network name (default: default)
  --loader PATH          OVMF code image
                         (default: /run/libvirt/nix-ovmf/edk2-x86_64-secure-code.fd)
  --nvram-template PATH  OVMF vars template
                         (default: /run/libvirt/nix-ovmf/edk2-i386-vars.fd)
  -h, --help             Show this help
EOF
}

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "missing required command: $1" >&2
        exit 1
    }
}

cleanup_on_error() {
    local exit_code="$?"

    if [[ "$exit_code" -ne 0 ]]; then
        if virsh -c qemu:///system dominfo "$NAME" >/dev/null 2>&1; then
            virsh -c qemu:///system destroy "$NAME" >/dev/null 2>&1 || true
            virsh -c qemu:///system undefine "$NAME" >/dev/null 2>&1 || true
        fi
        if virsh -c qemu:///system vol-info --pool "$STORAGE_POOL" "$NAME" >/dev/null 2>&1; then
            virsh -c qemu:///system vol-delete --pool "$STORAGE_POOL" "$NAME" >/dev/null 2>&1 || true
        fi
    fi

    rm -rf "$WORK_DIR"
}

NAME="debian-trixie-autopkgtest"
RELEASE="trixie"
STORAGE_POOL="pool"
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/keyforge/autopkgtest-libvirt"
SEED_DIR="/tmp/keyforge-autopkgtest-seeds"
MEMORY="2048"
VCPUS="2"
DISK_SIZE_GIB="20"
LOGIN_USER="autopkgtest"
LOGIN_PASSWORD=""
NETWORK_NAME="default"
UEFI_LOADER="/run/libvirt/nix-ovmf/edk2-x86_64-secure-code.fd"
UEFI_NVRAM_TEMPLATE="/run/libvirt/nix-ovmf/edk2-i386-vars.fd"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --name)
            NAME="${2:-}"
            shift 2
            ;;
        --release)
            RELEASE="${2:-}"
            shift 2
            ;;
        --pool)
            STORAGE_POOL="${2:-}"
            shift 2
            ;;
        --cache-dir)
            CACHE_DIR="${2:-}"
            shift 2
            ;;
        --seed-dir)
            SEED_DIR="${2:-}"
            shift 2
            ;;
        --memory)
            MEMORY="${2:-}"
            shift 2
            ;;
        --vcpus)
            VCPUS="${2:-}"
            shift 2
            ;;
        --size)
            DISK_SIZE_GIB="${2:-}"
            shift 2
            ;;
        --user)
            LOGIN_USER="${2:-}"
            shift 2
            ;;
        --password)
            LOGIN_PASSWORD="${2:-}"
            shift 2
            ;;
        --network)
            NETWORK_NAME="${2:-}"
            shift 2
            ;;
        --loader)
            UEFI_LOADER="${2:-}"
            shift 2
            ;;
        --nvram-template)
            UEFI_NVRAM_TEMPLATE="${2:-}"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

case "$RELEASE" in
    trixie)
        OSINFO="debian13"
        IMAGE_NAME="debian-13-genericcloud-amd64.qcow2"
        IMAGE_URL="https://cloud.debian.org/images/cloud/trixie/latest/${IMAGE_NAME}"
        ;;
    bookworm)
        OSINFO="debian12"
        IMAGE_NAME="debian-12-genericcloud-amd64.qcow2"
        IMAGE_URL="https://cloud.debian.org/images/cloud/bookworm/latest/${IMAGE_NAME}"
        ;;
    *)
        echo "unsupported release: $RELEASE" >&2
        exit 2
        ;;
esac

require_cmd virsh
require_cmd virt-install
require_cmd qemu-img
require_cmd wget
require_cmd mkfs.vfat
require_cmd mcopy
require_cmd openssl

if [[ "$(virsh -c qemu:///system net-info "$NETWORK_NAME" >/dev/null 2>&1; echo $?)" != "0" ]]; then
    echo "libvirt network not found: $NETWORK_NAME" >&2
    exit 1
fi

if ! virsh -c qemu:///system pool-info "$STORAGE_POOL" >/dev/null 2>&1; then
    echo "libvirt storage pool not found: $STORAGE_POOL" >&2
    exit 1
fi

if [[ ! -r "$UEFI_LOADER" ]]; then
    echo "UEFI loader not found: $UEFI_LOADER" >&2
    exit 1
fi

if [[ ! -r "$UEFI_NVRAM_TEMPLATE" ]]; then
    echo "UEFI NVRAM template not found: $UEFI_NVRAM_TEMPLATE" >&2
    exit 1
fi

if virsh -c qemu:///system dominfo "$NAME" >/dev/null 2>&1; then
    echo "domain already exists: $NAME" >&2
    exit 1
fi

if virsh -c qemu:///system vol-info --pool "$STORAGE_POOL" "$NAME" >/dev/null 2>&1; then
    echo "storage volume already exists in pool '$STORAGE_POOL': $NAME" >&2
    exit 1
fi

if [[ -z "$LOGIN_PASSWORD" ]]; then
    LOGIN_PASSWORD="$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | cut -c1-20)"
fi

BASE_IMAGE="${CACHE_DIR}/${RELEASE}-base.qcow2"
WORK_DIR="$(mktemp -d)"
trap cleanup_on_error EXIT

USER_DATA="${WORK_DIR}/user-data"
META_DATA="${WORK_DIR}/meta-data"
RAW_IMAGE="${WORK_DIR}/${NAME}.raw"
SEED_IMAGE="${SEED_DIR}/${NAME}-seed.img"

mkdir -p "$CACHE_DIR"
mkdir -p "$SEED_DIR"

if [[ ! -f "$BASE_IMAGE" ]]; then
    echo "Downloading Debian ${RELEASE} cloud image..."
    wget -O "$BASE_IMAGE.tmp" "$IMAGE_URL"
    mv "$BASE_IMAGE.tmp" "$BASE_IMAGE"
fi

echo "Creating raw zvol in libvirt pool '${STORAGE_POOL}'..."
virsh -c qemu:///system vol-create-as \
    "$STORAGE_POOL" \
    "$NAME" \
    "${DISK_SIZE_GIB}G" \
    --format raw >/dev/null

VM_IMAGE="$(
    virsh -c qemu:///system vol-path --pool "$STORAGE_POOL" "$NAME"
)"

echo "Converting cloud image to sparse raw staging file..."
qemu-img convert -f qcow2 -O raw -S 4k "$BASE_IMAGE" "$RAW_IMAGE"

echo "Uploading raw image into libvirt volume..."
virsh -c qemu:///system vol-upload \
    --pool "$STORAGE_POOL" \
    --vol "$NAME" \
    --file "$RAW_IMAGE" \
    --sparse >/dev/null

cat >"$USER_DATA" <<EOF
#cloud-config
users:
  - default
  - name: ${LOGIN_USER}
    lock_passwd: false
    passwd: $(openssl passwd -6 "$LOGIN_PASSWORD")
    groups: [adm, sudo]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
ssh_pwauth: true
disable_root: false
package_update: true
packages:
  - python3
  - qemu-guest-agent
  - sudo
runcmd:
  - [ systemctl, enable, serial-getty@ttyS0.service ]
  - [ systemctl, start, serial-getty@ttyS0.service ]
  - [ systemctl, enable, serial-getty@hvc0.service ]
  - [ systemctl, start, serial-getty@hvc0.service ]
  - [ systemctl, enable, qemu-guest-agent.service ]
  - [ systemctl, start, qemu-guest-agent.service ]
EOF

cat >"$META_DATA" <<EOF
instance-id: ${NAME}
local-hostname: ${NAME}
EOF

rm -f "$SEED_IMAGE"
truncate -s 16M "$SEED_IMAGE"
mkfs.vfat -n CIDATA "$SEED_IMAGE" >/dev/null
mcopy -oi "$SEED_IMAGE" "$USER_DATA" ::user-data
mcopy -oi "$SEED_IMAGE" "$META_DATA" ::meta-data
chmod 0644 "$SEED_IMAGE"

virt-install \
    --connect qemu:///system \
    --name "$NAME" \
    --memory "$MEMORY" \
    --vcpus "$VCPUS" \
    --machine q35 \
    --cpu host-passthrough \
    --import \
    --osinfo "$OSINFO" \
    --boot "loader=${UEFI_LOADER},loader.readonly=yes,loader.type=pflash,loader_secure=yes,nvram.template=${UEFI_NVRAM_TEMPLATE},firmware.feature0.name=secure-boot,firmware.feature0.enabled=yes,firmware.feature1.name=enrolled-keys,firmware.feature1.enabled=no" \
    --disk "vol=${STORAGE_POOL}/${NAME},device=disk,bus=virtio,format=raw" \
    --disk "path=${SEED_IMAGE},device=disk,bus=virtio,format=raw,readonly=on" \
    --network "network=${NETWORK_NAME},model=virtio" \
    --graphics none \
    --console pty,target.type=serial \
    --console pty,target.type=virtio \
    --rng /dev/urandom \
    --channel unix,target.type=virtio,name=org.qemu.guest_agent.0 \
    --noautoconsole

trap 'rm -rf "$WORK_DIR"' EXIT

cat <<EOF
Created VM: ${NAME}
Image: ${VM_IMAGE}
Pool: ${STORAGE_POOL}
Seed image: ${SEED_IMAGE}
Release: ${RELEASE}
Login user: ${LOGIN_USER}
Login password: ${LOGIN_PASSWORD}

Suggested autopkgtest command:
  autopkgtest . -- qemu -u ${LOGIN_USER} -p ${LOGIN_PASSWORD} ${VM_IMAGE}

Suggested helper command:
  packaging/debian/run-autopkgtest-libvirt.sh --domain ${NAME} --user ${LOGIN_USER} --password '${LOGIN_PASSWORD}'
EOF
