"""Restore node permissions before asking udev to apply current desktop policy."""

from __future__ import annotations

import json
import os
import stat
from typing import TYPE_CHECKING, cast

from keymasq.common.types import JsonObject
from keymasq.masking.backend import finish_io, run_host, save_json

if TYPE_CHECKING:
    from keymasq.masking.backend import LinuxMaskBackend
    from keymasq.masking.inventory import Attachment


def acl_entries(acl: str) -> set[str]:
    return {entry for line in acl.splitlines() if (entry := line.split("#", 1)[0].strip())}


def static_acl(acl: str, *, uaccess: bool) -> str:
    entries = acl_entries(acl)
    if uaccess:
        # POSIX ACLs do not record provenance. Named users on a seat-managed
        # node must be regenerated by current policy, never by an old snapshot.
        entries = {
            entry
            for entry in entries
            if not entry.startswith("user:") or entry.startswith("user::")
        }
    if not any(entry.startswith(("user:", "group:")) and entry.split(":")[1] for entry in entries):
        mask = next((entry.split(":")[-1] for entry in entries if entry.startswith("mask:")), None)
        if mask is not None:
            entries = {
                "group::"
                + "".join(
                    right if right == limit else "-"
                    for right, limit in zip(entry.split(":")[-1], mask, strict=True)
                )
                if entry.startswith("group::")
                else entry
                for entry in entries
            }
        entries = {entry for entry in entries if not entry.startswith("mask:")}
    return "\n".join(sorted(entries)) + "\n"


async def capture(backend: LinuxMaskBackend, attachment: Attachment) -> None:
    """Capture once, before even an offline selector installs its first rule."""
    if backend.armed or backend.permissions.exists():
        return
    nodes: dict[str, JsonObject] = {}
    for node in await finish_io(backend.inventory.nodes, attachment):
        info = await finish_io(node.stat)
        if not stat.S_ISCHR(info.st_mode):
            raise ValueError("Hardware node changed before permission capture")
        role = await finish_io(backend.inventory.node_role, attachment, node)
        if role in nodes:
            raise ValueError(f"Ambiguous hardware interface role: {role}")
        properties = await run_host("udevadm", "info", "--query=property", f"--name={node}")
        uaccess = any(
            "uaccess" in line.split("=", 1)[1].split(":")
            for line in properties.splitlines()
            if line.startswith(("TAGS=", "CURRENT_TAGS="))
        )
        acl = await run_host("getfacl", "-cn", "--", str(node))
        nodes[role] = {
            "uid": info.st_uid,
            "gid": info.st_gid,
            "acl": static_acl(acl, uaccess=uaccess),
        }
    await finish_io(
        save_json, backend.permissions, {"selector": backend.selector(attachment), "nodes": nodes}
    )


async def restore(backend: LinuxMaskBackend, attachment: Attachment, journal: JsonObject) -> None:
    if backend.permissions.exists():
        record = json.loads(await finish_io(backend.permissions.read_text))
        snapshots = cast(dict[str, JsonObject], record["nodes"])
    else:
        # An interrupted older helper may have only a journal. It did not
        # distinguish desktop grants, so do not replay any named user entries.
        snapshots = {} if journal.get("prearmed") else cast(dict[str, JsonObject], journal["nodes"])
        snapshots = {
            role: {**item, "acl": static_acl(str(item["acl"]), uaccess=True)}
            for role, item in snapshots.items()
        }
    acl_file = backend.runtime_dir / "restore.acl"
    try:
        for node in await finish_io(backend.inventory.nodes, attachment):
            role = await finish_io(backend.inventory.node_role, attachment, node)
            baseline = snapshots.get(
                role, {"uid": 0, "gid": 0, "acl": "user::rw-\ngroup::---\nother::---\n"}
            )
            uid, gid = int(str(baseline["uid"])), int(str(baseline["gid"]))
            acl = str(baseline["acl"])
            await finish_io(os.chown, node, uid, gid)
            await finish_io(acl_file.write_text, acl)
            await run_host("setfacl", f"--set-file={acl_file}", "--", str(node))
            info = await finish_io(node.stat)
            actual_acl = await run_host("getfacl", "-cn", "--", str(node))
            if (info.st_uid, info.st_gid) != (uid, gid) or acl_entries(actual_acl) != acl_entries(
                acl
            ):
                raise OSError(f"Could not restore baseline permissions for {node.name}")
    finally:
        await finish_io(acl_file.unlink, missing_ok=True)
