daemon_allowed_uids = []
session_allowed_uids = []

[macro]
exec_timeout_max_ms = 30000

[gui]
emergency_cancel_combo_enabled = true

[recording_guard]
macro_recording_allowed = true
macro_recording_time_limit = 10
