from .gnome import GNOME_ACTION_DEFINITION
from .hyprland import HYPRLAND_ACTION_DEFINITION
from .kde import KDE_ACTION_DEFINITION
from .niri import NIRI_ACTION_DEFINITION

COMPOSITOR_ACTION_DEFINITIONS = (
    HYPRLAND_ACTION_DEFINITION,
    NIRI_ACTION_DEFINITION,
    GNOME_ACTION_DEFINITION,
    KDE_ACTION_DEFINITION,
)
