#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"

COMMON_METADATA = {
    "maintainer": "nyrda <nyrda@keyforge.tools>",
    "pkgname": "keyforge",
    "pkgrel": "1",
    "pkgdesc": "A key remapping tool for Linux using evdev and uinput",
    "arch": ["any"],
    "url": "https://github.com/nyrda/keyforge",
    "license": ["MIT"],
    "depends": [
        "acl",
        "slurp",
        "python>=3.12",
        "python-evdev>=1.6.0",
        "python-tomli-w>=1.0.0",
        "python-dbus-next>=0.2.3",
        "python-xlib>=0.33",
        "python-gobject>=3.42.0",
        "gtk4",
        "libadwaita",
        "polkit",
        "systemd",
    ],
    "makedepends": [
        "python-setuptools>=61.0",
        "python-wheel",
        "python-build",
        "python-installer",
    ],
    "optdepends": [
        "hyprland: for Hyprland window rule support",
    ],
}

LOCAL_PREPARE = """prepare() {
    local worktree_dir="$srcdir/$pkgname-$pkgver"

    rm -rf "$worktree_dir"
    mkdir -p "$worktree_dir"

    shopt -s dotglob nullglob
    local entry
    local base_name
    for entry in "$startdir"/*; do
        base_name="${entry##*/}"
        case "$base_name" in
            .git|.direnv|.mypy_cache|.pytest_cache|.ruff_cache|.venv|dist|pkg|src|*.pkg.tar.*|*.src.tar.*)
                continue
                ;;
        esac
        cp -a "$entry" "$worktree_dir"/
    done
    shopt -u dotglob nullglob
}"""

def read_version() -> str:
    pyproject = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text())
    project = pyproject["project"]
    version = project["version"]
    if not isinstance(version, str):
        raise TypeError("project.version must be a string")
    return version


def parse_args(pkgver: str) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render pacman packaging files for the local checkout and the AUR subtree."
    )
    parser.add_argument(
        "--pkgver",
        default=pkgver,
        help="Package version to embed in generated pacman packaging files.",
    )
    parser.add_argument(
        "--aur-source-url",
        default=f"{COMMON_METADATA['url']}/releases/download/v{pkgver}/keyforge-{pkgver}.tar.gz",
        help="Release tarball URL to embed in packaging/aur/PKGBUILD.",
    )
    parser.add_argument(
        "--aur-sha256",
        default="SKIP",
        help="SHA256 for the release tarball embedded in packaging/aur/PKGBUILD and .SRCINFO.",
    )
    return parser.parse_args()


def format_array(values: list[str], indent: str = "    ") -> str:
    return "\n".join(f"{indent}'{value}'" for value in values)


def render_template(name: str, replacements: dict[str, str]) -> str:
    content = (TEMPLATES_DIR / name).read_text()
    for key, value in replacements.items():
        content = content.replace(f"@{key}@", value)
    return content


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text() == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def build_replacements(
    pkgver: str,
    variant: str,
    aur_source_url: str,
    aur_sha256: str,
) -> dict[str, str]:
    generated_comment = (
        "# Generated by `python3 packaging/pacman/render.py`.\n"
        "# Do not edit this file directly; update `packaging/pacman/templates/`."
    )
    replacements = {
        "GENERATED_COMMENT": generated_comment,
        "MAINTAINER": COMMON_METADATA["maintainer"],
        "PKGNAME": COMMON_METADATA["pkgname"],
        "PKGVER": pkgver,
        "PKGREL": COMMON_METADATA["pkgrel"],
        "PKGDESC": COMMON_METADATA["pkgdesc"],
        "ARCH": format_array(COMMON_METADATA["arch"]),
        "URL": COMMON_METADATA["url"],
        "LICENSE": format_array(COMMON_METADATA["license"]),
        "DEPENDS": format_array(COMMON_METADATA["depends"]),
        "MAKEDEPENDS": format_array(COMMON_METADATA["makedepends"]),
        "OPTDEPENDS": format_array(COMMON_METADATA["optdepends"]),
        "PREPARE_BLOCK": "",
        "SOURCE_BLOCK": "source=()",
        "SHA256SUMS_BLOCK": "sha256sums=()",
        "AUR_RELEASE_NOTE": "",
    }
    if variant == "local":
        replacements["PREPARE_BLOCK"] = LOCAL_PREPARE
    elif variant == "aur":
        replacements["SOURCE_BLOCK"] = (
            f'source=("$pkgname-$pkgver.tar.gz::{aur_source_url}")'
        )
        replacements["SHA256SUMS_BLOCK"] = f"sha256sums=('{aur_sha256}')"
    else:
        raise ValueError(f"unknown variant: {variant}")
    return replacements


def build_srcinfo(pkgver: str, aur_source_url: str, aur_sha256: str) -> str:
    lines = [
        f"pkgbase = {COMMON_METADATA['pkgname']}",
        f"\tpkgdesc = {COMMON_METADATA['pkgdesc']}",
        f"\tpkgver = {pkgver}",
        f"\tpkgrel = {COMMON_METADATA['pkgrel']}",
        f"\turl = {COMMON_METADATA['url']}",
    ]
    for arch in COMMON_METADATA["arch"]:
        lines.append(f"\tarch = {arch}")
    for license_name in COMMON_METADATA["license"]:
        lines.append(f"\tlicense = {license_name}")
    for makedepend in COMMON_METADATA["makedepends"]:
        lines.append(f"\tmakedepends = {makedepend}")
    for depend in COMMON_METADATA["depends"]:
        lines.append(f"\tdepends = {depend}")
    for optdepend in COMMON_METADATA["optdepends"]:
        lines.append(f"\toptdepends = {optdepend}")
    lines.extend(
        [
            f"\tsource = keyforge-{pkgver}.tar.gz::{aur_source_url}",
            f"\tsha256sums = {aur_sha256}",
            "\tinstall = keyforge.install",
            "",
            f"pkgname = {COMMON_METADATA['pkgname']}",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    pkgver = os.environ.get("KEYFORGE_PKGVER_OVERRIDE") or read_version()
    args = parse_args(pkgver)
    local_replacements = build_replacements(
        args.pkgver, "local", args.aur_source_url, args.aur_sha256
    )
    aur_replacements = build_replacements(
        args.pkgver, "aur", args.aur_source_url, args.aur_sha256
    )

    write_if_changed(REPO_ROOT / "PKGBUILD", render_template("PKGBUILD.in", local_replacements))
    write_if_changed(
        REPO_ROOT / "keyforge.install",
        render_template("keyforge.install.in", local_replacements),
    )
    write_if_changed(
        REPO_ROOT / "packaging/aur/PKGBUILD",
        render_template("PKGBUILD.in", aur_replacements),
    )
    write_if_changed(
        REPO_ROOT / "packaging/aur/keyforge.install",
        render_template("keyforge.install.in", aur_replacements),
    )
    write_if_changed(
        REPO_ROOT / "packaging/aur/.SRCINFO",
        build_srcinfo(args.pkgver, args.aur_source_url, args.aur_sha256),
    )


if __name__ == "__main__":
    main()
